# Using python as a base
FROM python:3

# Copying pipenv relevant files
COPY ./Pipfile /app/
COPY ./Pipfile.lock /app/
WORKDIR /app

# Installing pipenv
RUN pip install pipenv

# Installing dependencies to system python
RUN pipenv install --system --deploy

