version: 2
jobs:
  build:
    docker:
      - image: kombustor/python3-dlib

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
        - pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
        - pip-packages-v1-{{ .Branch }}-
        - pip-packages-v1-
      - run:
          name: Install Dependencies
          command: |
            pip install pipenv
            pipenv install --system --deploy
      - save_cache:
          key: pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - "~/.cache/pip"
            - "~/.cache/pipenv"
            - /usr/local/lib/python3.7/site-packages
      - run:
          name: Run Linter
          command: |
            flake8 --exclude=.venv* --statistics