version: 2
jobs:
  build:
    docker:
      - image: kombustor/python3-dlib

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: install dependencies
          command: |
            pip install pipenv
            pipenv install --system --deploy
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
      - run:
          name: run linter
          command: |
            flake8 --exclude=.venv* --statistics