version: 2
jobs:
  build:
    docker:
      - image: kombustor/python3-dlib

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - pip-packages-v1-{{ .Branch }}-
            - pip-packages-v1-
      - run:
          name: Install Dependencies
          command: |
            apk add --no-cache postgresql-dev
            pip install pipenv
            pipenv install --dev --system --deploy
      - save_cache:
          key: pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - "~/.cache/pip"
            - "~/.cache/pipenv"
      - run:
          name: Run Linter
          command: |
            flake8 --exclude=.venv* --statistics
      - run:
          name: Run Tests
          command: |
            pytest -v --cov=lensor --junitxml=test-reports/junit.xml

      - store_test_results:
          path: test-reports
