version: '3.7'

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env/db.env
    networks:
      - internal

  pgadmin4:
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
    - db
    volumes:
    - ${PWD}/.devcontainer/pgadmin4/servers.json:/pgadmin4/servers.json
    ports:
    - "8888:80"
    env_file:
    - .env/pgadmin4.env
    networks:
    - internal
    - external

  lensor:
    build:
      context: '..'
      dockerfile: .devcontainer/Dockerfile
    restart: unless-stopped
    command: /bin/sh -c "while sleep 1; do :; done"
    depends_on:
      - db
    env_file:
      - .env/db.env
    networks:
      - internal
      - external
    volumes:
      - ..:/workspace

volumes:
  db:

networks:
  internal:
  external:
