version: '3.7'

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - db.env
    networks:
      - internal

  lensor:
    build:
      context: '..'
      dockerfile: .devcontainer/Dockerfile
    restart: unless-stopped
    command: /bin/sh -c "while sleep 1; do :; done"
    depends_on:
      - db
    env_file:
      - db.env
    networks:
      - internal
      - external
    volumes:
      - ..:/workspace

volumes:
  db:

networks:
  internal:
  external:
