version: '3.7'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes: 
      - db:/var/lib/postgresql/data
    env_file:
      - db.env
    networks:
      - internal

  app:
    build:
      context: '..'
      dockerfile: .devcontainer/Dockerfile
    restart: always
    depends_on:
      - db
    env_file:
      - db.env
    networks:
      - internal
      - external

volumes:
  db:

networks:
  internal:
  external: