version: '3.7'

service:
  db:
    image: postgres:alpine
    restart: always
    volumes: db:/var/lib/postgresql/data
    env_file:
      - ./.devcontainer/db.env
    networks:
      - internal

  app:
    build:
      context: './.devcontainer'
      dockerfile: Dockerfile
    restar: always
    depends_on:
      -db
    env_file:
      - ./.devcontainer/db.env'
    networks:
      - internal
      - external

volumes:
  db:

network:
  internal:
  external: